import React, { useState } from 'react';
import { Download, Heart, Eye, Filter, Sparkles, Share2, Layers, Search, Check } from 'lucide-react';
import { ModelAsset } from '../types';
import { InteractiveModelViewer } from './InteractiveModelViewer';

interface ModelGalleryProps {
  assets: ModelAsset[];
  onSelectModel: (asset: ModelAsset) => void;
}

export const ModelGallery: React.FC<ModelGalleryProps> = ({ assets, onSelectModel }) => {
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  const [searchQuery, setSearchQuery] = useState('');
  const [activeModalAsset, setActiveModalAsset] = useState<ModelAsset | null>(null);
  const [likedAssets, setLikedAssets] = useState<Record<string, boolean>>({});
  const [downloadedAssetId, setDownloadedAssetId] = useState<string | null>(null);

  const categories = ['All', 'Sci-Fi', 'Characters', 'Props', 'Vehicles', 'Architecture'];

  const filteredAssets = assets.filter((asset) => {
    const matchesCategory = selectedCategory === 'All' || asset.category === selectedCategory;
    const matchesSearch =
      asset.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      asset.prompt.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  const toggleLike = (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    setLikedAssets((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  const handleDownload = (e: React.MouseEvent, asset: ModelAsset) => {
    e.stopPropagation();
    setDownloadedAssetId(asset.id);
    setTimeout(() => setDownloadedAssetId(null), 2000);

    // Create a simple text export file representation
    const element = document.createElement('a');
    const file = new Blob(
      [
        JSON.stringify(
          {
            title: asset.title,
            polyCount: asset.polyCount,
            creator: asset.creator,
            prompt: asset.prompt,
            format: asset.format,
            notice: 'Hyper3D Asset Export Package',
          },
          null,
          2
        ),
      ],
      { type: 'application/json' }
    );
    element.href = URL.createObjectURL(file);
    element.download = `${asset.title.toLowerCase().replace(/\s+/g, '_')}_model.json`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="w-full flex flex-col gap-6 py-8">
      {/* Header and Filter Controls */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight flex items-center gap-2">
            Explore 3D Showcase
            <span className="text-xs font-mono font-normal px-2.5 py-0.5 rounded-full bg-purple-500/20 text-purple-300 border border-purple-500/30">
              Community Generations
            </span>
          </h2>
          <p className="text-sm text-neutral-400 mt-1">
            Inspect, manipulate, and download high-precision 3D assets generated by Hyper3D AI.
          </p>
        </div>

        {/* Search Input */}
        <div className="relative w-full md:w-72">
          <Search className="w-4 h-4 text-neutral-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            id="gallery-search-input"
            type="text"
            placeholder="Search prompts or models..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-neutral-900 border border-white/10 rounded-xl pl-10 pr-4 py-2 text-xs sm:text-sm text-white placeholder-neutral-500 focus:outline-none focus:border-pink-500 transition-colors"
          />
        </div>
      </div>

      {/* Category Filter Pills */}
      <div className="flex items-center gap-2 overflow-x-auto pb-2 scrollbar-none">
        {categories.map((cat) => (
          <button
            key={cat}
            onClick={() => setSelectedCategory(cat)}
            className={`px-4 py-2 rounded-xl text-xs sm:text-sm font-medium whitespace-nowrap transition-all ${
              selectedCategory === cat
                ? 'bg-white text-neutral-950 font-semibold shadow-lg shadow-white/10'
                : 'bg-neutral-900/80 text-neutral-400 hover:text-white hover:bg-neutral-800 border border-white/5'
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Grid of 3D Assets */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {filteredAssets.map((asset) => {
          const isLiked = likedAssets[asset.id];
          return (
            <div
              key={asset.id}
              onClick={() => setActiveModalAsset(asset)}
              className="group relative bg-neutral-900/60 border border-white/10 hover:border-pink-500/50 rounded-2xl overflow-hidden backdrop-blur-md cursor-pointer transition-all duration-300 hover:-translate-y-1 hover:shadow-2xl hover:shadow-pink-500/10 flex flex-col"
            >
              {/* Thumbnail / 3D Canvas Preview */}
              <div className="relative h-56 w-full bg-neutral-950 overflow-hidden">
                <InteractiveModelViewer
                  modelType={asset.modelType}
                  primaryColor={asset.primaryColor}
                  autoRotate={true}
                />

                {/* Top Badge */}
                <div className="absolute top-3 left-3 bg-black/60 backdrop-blur-md px-2.5 py-1 rounded-lg text-[10px] font-mono text-white border border-white/10 flex items-center gap-1">
                  <Layers className="w-3 h-3 text-pink-400" />
                  {(asset.polyCount / 1000).toFixed(1)}k Polys
                </div>

                {/* Like Button */}
                <button
                  onClick={(e) => toggleLike(e, asset.id)}
                  className={`absolute top-3 right-3 p-2 rounded-xl backdrop-blur-md border border-white/10 transition-all ${
                    isLiked
                      ? 'bg-rose-500 text-white border-rose-400'
                      : 'bg-black/60 text-neutral-300 hover:text-white hover:bg-black/80'
                  }`}
                >
                  <Heart className={`w-3.5 h-3.5 ${isLiked ? 'fill-current' : ''}`} />
                </button>
              </div>

              {/* Asset Info Body */}
              <div className="p-4 flex flex-col justify-between flex-grow gap-3">
                <div>
                  <div className="flex items-center justify-between text-xs text-neutral-400 mb-1">
                    <span className="text-pink-400 font-medium">{asset.category}</span>
                    <span className="font-mono text-[11px] text-neutral-500">{asset.generationTime}</span>
                  </div>
                  <h3 className="text-sm font-semibold text-white group-hover:text-pink-300 transition-colors line-clamp-1">
                    {asset.title}
                  </h3>
                  <p className="text-xs text-neutral-400 line-clamp-2 mt-1 font-normal leading-relaxed">
                    "{asset.prompt}"
                  </p>
                </div>

                {/* Formats & Actions */}
                <div className="pt-3 border-t border-white/5 flex items-center justify-between">
                  <div className="flex items-center gap-1">
                    {asset.format.map((fmt) => (
                      <span
                        key={fmt}
                        className="px-1.5 py-0.5 rounded bg-white/5 text-[10px] font-mono text-neutral-400 border border-white/5"
                      >
                        {fmt}
                      </span>
                    ))}
                  </div>

                  <button
                    onClick={(e) => handleDownload(e, asset)}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-purple-600/20 hover:bg-purple-600 text-purple-300 hover:text-white border border-purple-500/30 text-xs font-medium transition-all"
                  >
                    {downloadedAssetId === asset.id ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-emerald-400" />
                        <span>Saved</span>
                      </>
                    ) : (
                      <>
                        <Download className="w-3.5 h-3.5" />
                        <span>Export</span>
                      </>
                    )}
                  </button>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Modal Detail Viewer when an asset is clicked */}
      {activeModalAsset && (
        <div className="fixed inset-0 z-50 bg-neutral-950/80 backdrop-blur-xl flex items-center justify-center p-4 sm:p-6 animate-fade-in">
          <div className="relative w-full max-w-4xl bg-neutral-900 border border-white/15 rounded-3xl p-6 sm:p-8 shadow-2xl flex flex-col lg:flex-row gap-6 max-h-[90vh] overflow-y-auto">
            <button
              onClick={() => setActiveModalAsset(null)}
              className="absolute top-4 right-4 text-neutral-400 hover:text-white p-2 rounded-full bg-neutral-800/80 hover:bg-neutral-700 transition-colors"
            >
              ✕
            </button>

            {/* Modal Left 3D Viewport */}
            <div className="w-full lg:w-1/2 h-80 lg:h-auto min-h-[300px]">
              <InteractiveModelViewer
                modelType={activeModalAsset.modelType}
                primaryColor={activeModalAsset.primaryColor}
                autoRotate={true}
              />
            </div>

            {/* Modal Right Info */}
            <div className="w-full lg:w-1/2 flex flex-col justify-between gap-6">
              <div>
                <span className="px-2.5 py-1 rounded-md bg-pink-500/20 text-pink-300 text-xs font-semibold border border-pink-500/30">
                  {activeModalAsset.category} Asset
                </span>
                <h2 className="text-xl sm:text-2xl font-bold text-white mt-3">{activeModalAsset.title}</h2>
                <p className="text-xs text-neutral-400 mt-2 bg-neutral-950 p-3 rounded-xl border border-white/5 font-mono">
                  "{activeModalAsset.prompt}"
                </p>

                {/* Specs list */}
                <div className="grid grid-cols-2 gap-3 mt-4 text-xs font-mono">
                  <div className="p-3 bg-neutral-950 rounded-xl border border-white/5">
                    <span className="text-neutral-500 block">Polygon Count</span>
                    <span className="text-white font-semibold">{activeModalAsset.polyCount.toLocaleString()} Quads</span>
                  </div>
                  <div className="p-3 bg-neutral-950 rounded-xl border border-white/5">
                    <span className="text-neutral-500 block">Gen Duration</span>
                    <span className="text-emerald-400 font-semibold">{activeModalAsset.generationTime}</span>
                  </div>
                  <div className="p-3 bg-neutral-950 rounded-xl border border-white/5">
                    <span className="text-neutral-500 block">Texture PBR</span>
                    <span className="text-purple-400 font-semibold">4K Metallic/Roughness</span>
                  </div>
                  <div className="p-3 bg-neutral-950 rounded-xl border border-white/5">
                    <span className="text-neutral-500 block">Creator</span>
                    <span className="text-cyan-400 font-semibold">{activeModalAsset.creator}</span>
                  </div>
                </div>
              </div>

              {/* Export Buttons */}
              <div className="flex items-center gap-3 pt-4 border-t border-white/10">
                <button
                  onClick={(e) => handleDownload(e, activeModalAsset)}
                  className="flex-1 py-3 px-4 rounded-xl bg-gradient-to-r from-pink-500 to-purple-600 text-white font-semibold text-sm flex items-center justify-center gap-2 hover:shadow-lg hover:shadow-pink-500/25 transition-all"
                >
                  <Download className="w-4 h-4" />
                  Download GLTF / OBJ Package
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
